package core.observer.events;

public enum SystemEventType {
    BUS_POSITION_UPDATED,
    DATAGRAM_PROCESSED,
    DATAGRAM_INVALID,
    ROUTE_CATALOG_LOADED,
    ROUTES_LOADED,
    STREAM_STARTED,
    STREAM_FINISHED,
    PROCESSING_ERROR,
    BASIC_ALERT_CREATED,
    OPERATIONAL_EVENT_CREATED,
    ALERT_CREATED,
    DRIVER_EVENT_SENT,
    EVENT_PROCESSING_ERROR
}
