allprojects {

    repositories {
        mavenCentral()
    }
}

subprojects {

    apply plugin: 'java'

    if (project.name == 'MasterNode' || project.name == 'WorkerNode') {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8
    } else {
        sourceCompatibility = 1.8
        targetCompatibility = 1.8

        dependencies {

            implementation 'com.zeroc:ice:3.7.10'

            implementation 'org.postgresql:postgresql:42.2.27'
        }
    }
}
