CREATE TABLE IF NOT EXISTS zones (
    id SERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS routes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_name VARCHAR(50) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS buses (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    plate VARCHAR(30),
    status VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
    route_id INTEGER REFERENCES routes(id),
    zone_id INTEGER REFERENCES zones(id)
);

CREATE TABLE IF NOT EXISTS datagrams (
    id BIGSERIAL PRIMARY KEY,
    source_datagram_id VARCHAR(80),
    bus_id BIGINT REFERENCES buses(id),
    bus_code VARCHAR(80) NOT NULL,
    route_id INTEGER REFERENCES routes(id),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    speed DOUBLE PRECISION,
    event_code VARCHAR(80),
    timestamp TIMESTAMP NOT NULL,
    raw_payload TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bus_positions (
    id BIGSERIAL PRIMARY KEY,
    bus_id BIGINT REFERENCES buses(id),
    bus_code VARCHAR(80) NOT NULL,
    route_id INTEGER REFERENCES routes(id),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    speed DOUBLE PRECISION,
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operational_events (
    id BIGSERIAL PRIMARY KEY,
    bus_id BIGINT REFERENCES buses(id),
    bus_code VARCHAR(80),
    route_id INTEGER REFERENCES routes(id),
    event_code VARCHAR(80),
    event_type VARCHAR(80),
    priority VARCHAR(30),
    description TEXT,
    source_type VARCHAR(40),
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    timestamp TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
    id BIGSERIAL PRIMARY KEY,
    event_id BIGINT REFERENCES operational_events(id),
    priority VARCHAR(30),
    title VARCHAR(120),
    message TEXT,
    acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS route_statistics (
    id BIGSERIAL PRIMARY KEY,
    route_id INTEGER REFERENCES routes(id),
    month INTEGER,
    year INTEGER,
    average_speed DOUBLE PRECISION,
    event_count INTEGER DEFAULT 0,
    processed_datagrams INTEGER DEFAULT 0,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS throughput_metrics (
    id BIGSERIAL PRIMARY KEY,
    dataset_type VARCHAR(30) NOT NULL,
    processed_events INTEGER DEFAULT 0,
    processed_datagrams INTEGER DEFAULT 0,
    processing_time DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS administrators (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS controller_users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    assigned_zone INTEGER REFERENCES zones(id),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS sessions (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    role VARCHAR(50) NOT NULL,
    login_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMP,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Phase 5 security users. national_id is stored as VARCHAR(10) because it represents a cedula.
CREATE TABLE IF NOT EXISTS system_users (
    id BIGSERIAL PRIMARY KEY,
    national_id VARCHAR(10) NOT NULL UNIQUE,
    full_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL CHECK (role IN ('ADMIN', 'CONTROLLER', 'DRIVER')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Operational zones are logical groups of routes, not geographic polygons.
CREATE TABLE IF NOT EXISTS operational_zones (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    description VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS zone_route_assignments (
    id BIGSERIAL PRIMARY KEY,
    zone_id BIGINT NOT NULL REFERENCES operational_zones(id),
    route_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (zone_id, route_id)
);

COMMENT ON COLUMN zone_route_assignments.route_id IS
'LINEID numerico del CSV de rutas. No almacena shortName y no usa FK a routes(id) para evitar conflictos con seeds legacy.';

CREATE TABLE IF NOT EXISTS controller_zone_assignments (
    id BIGSERIAL PRIMARY KEY,
    controller_user_id BIGINT NOT NULL REFERENCES system_users(id),
    zone_id BIGINT NOT NULL REFERENCES operational_zones(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (controller_user_id, zone_id)
);

COMMENT ON TABLE controller_zone_assignments IS
'La validacion de que controller_user_id tenga rol CONTROLLER se hara en la capa de servicio futura.';

CREATE TABLE IF NOT EXISTS public_transport_estimates (
    id BIGSERIAL PRIMARY KEY,
    route_id INTEGER REFERENCES routes(id),
    average_travel_time DOUBLE PRECISION,
    average_speed DOUBLE PRECISION,
    congestion_level VARCHAR(40),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
